# Generated by Django 3.1.7 on 2021-04-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210427_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_time'], 'verbose_name_plural': 'Comments'},
        ),
    ]
