# Generated by Django 3.1.7 on 2021-04-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210427_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
